server:
  port: 80
  error:
    include-stacktrace: always
  ssl:
    enabled: false
logging:
  level:
    ru.sovaowltv.contoller.website: debug
    ru.sovaowltv.service.io: debug
    ru.sovaowltv.service.user.UsersRepositoryHandler: debug